meta_product_name: "Fantasy Politics"
meta_title: "Fantasy Politics | Be a political player"
meta_description: "Think you could do a better job than Theresa May? Build your cabinet here."
meta_image: "meta_image.png"                       # should exist in `app/assets/images/`
twitter_account: "@FantasyPolitic1"
